### ISSUE TITLE
How to use this crates with tokio async runtime

### ISSUE THREAD

**Issue by nanakura** [edreed/rust-spdk#46]
How to use this crates in tokio

**Comment by edreed** [comment]
@nanakura You would need to create a separate tokio runtime and run it side-by-side with this SPDK runtime. You can look at how mayastor does it [here](https://github.com/openebs/mayastor/blob/09f9189113c9f37117782420f4335dc819a90899/io-engine/src/core/runtime.rs#L53C1-L54C1) as an example. However, much of the tokio primitives cannot be run inside of the SPDK runtime, so you'll need to use a runtime-agnostic mechanism like those in [futures::channel](https://docs.rs/futures/0.3.30/futures/channel/index.html) to communicate between tokio and SPDK tasks.

Also be aware that this is currently a personal project I am using to practice and learn more about Rust, asynchronous runtimes and the SPDK. It is not ready for general consumption.
